on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: NPM install
        run: npm install

      - name: NPM Build
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Publish
        id: publish
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Tag
        id: tag
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: kierans/gh-action-tag-on-npm-version@master
        with:
          git-user-name: github-actions
          git-user-email: github-actions@github.com

      - name: Release
        if: ${{ steps.tag.outputs.tag-created == 'true' }}
        uses: eloquent/github-release-action@v3
